/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai2;
import javax.swing.JPanel;
import javax.swing.GroupLayout;
import java.awt.Color;

/**
 *
 * @author admin
 */
public class baitap2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(baitap2.class.getName());

    /**
     * Creates new form baitap2
     */
    public baitap2() {
    initComponents(); // code xám, kệ nó
    myInit();         // code tự viết
}
private void myInit() {
    setTitle("Lê Văn A - TT601K14");
    setLocationRelativeTo(null);

    // ===== Tạo 7 JPanel =====
    JPanel p1 = new JPanel();
    JPanel p2 = new JPanel();
    JPanel p3 = new JPanel();
    JPanel p4 = new JPanel();
    JPanel p5 = new JPanel();
    JPanel p6 = new JPanel();
    JPanel p7 = new JPanel();

    // ===== Màu sắc =====
    p1.setBackground(Color.RED);
    p2.setBackground(Color.ORANGE);
    p3.setBackground(Color.YELLOW);
    p4.setBackground(Color.GREEN);

    p5.setBackground(Color.CYAN);
    p6.setBackground(Color.PINK);

    p7.setBackground(Color.BLUE);

    // ===== Xóa layout cũ (code xám tạo ra) =====
    getContentPane().removeAll();

    // ===== GroupLayout mới =====
    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);

    layout.setAutoCreateGaps(true);
    layout.setAutoCreateContainerGaps(true);

    // ===== Horizontal =====
    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)

            // Hàng trên: 4 panel ngang
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1)
                .addComponent(p2)
                .addComponent(p3)
                .addComponent(p4)
            )

            // Hàng giữa: trái - phải
            .addGroup(layout.createSequentialGroup()
                .addComponent(p5)
                .addComponent(p6)
            )

            // Hàng dưới
            .addComponent(p7)
    );

    // ===== Vertical =====
    layout.setVerticalGroup(
        layout.createSequentialGroup()

            // Hàng trên
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(p1)
                .addComponent(p2)
                .addComponent(p3)
                .addComponent(p4)
            )

            // Hàng giữa
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(p5)
                .addComponent(p6)
            )

            // Hàng dưới
            .addComponent(p7)
    );

    revalidate();
    repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new baitap2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
