/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai3;
import javax.swing.JPanel;
import javax.swing.GroupLayout;
import javax.swing.BorderFactory;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author admin
 */
public class baitap3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(baitap3.class.getName());

    /**
     * Creates new form baitap3
     */
    public baitap3() {
    initComponents(); // code xám, kệ nó
    myInit();         // code tự viết
}
private void myInit() {
    setTitle("Lê Văn A - TT601K14");
    setLocationRelativeTo(null);

    // ===== Panel chính =====
    JPanel p1 = new JPanel();
    JPanel p2 = new JPanel();
    JPanel p3 = new JPanel();
    JPanel p4 = new JPanel();
    JPanel p5 = new JPanel();
    JPanel p6 = new JPanel();
    JPanel p7 = new JPanel(); // panel chứa

    // ===== Kích thước =====
    Dimension size = new Dimension(100, 100);
    p1.setPreferredSize(size);
    p2.setPreferredSize(size);
    p3.setPreferredSize(size);
    p4.setPreferredSize(size);
    p5.setPreferredSize(size);
    p6.setPreferredSize(size);

    // ===== Màu nền =====
    p1.setBackground(new Color(173, 216, 230)); // xanh nhạt
    p2.setBackground(new Color(144, 238, 144)); // xanh lá nhạt
    p3.setBackground(new Color(216, 191, 216)); // xanh tím nhạt
    p4.setBackground(new Color(255, 182, 193)); // đỏ nhạt
    p5.setBackground(Color.YELLOW);
    p6.setBackground(new Color(64, 224, 208));  // xanh ngọc

    // ===== Border =====
    p1.setBorder(BorderFactory.createBevelBorder(1));
    p2.setBorder(BorderFactory.createEtchedBorder());
    p3.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
    p4.setBorder(BorderFactory.createMatteBorder(5, 5, 5, 5, Color.RED));
    p5.setBorder(BorderFactory.createSoftBevelBorder(0));
    p6.setBorder(BorderFactory.createTitledBorder("Panel 6"));

    // ===== Panel 7 chứa Panel 2 & 3 =====
    GroupLayout subLayout = new GroupLayout(p7);
    p7.setLayout(subLayout);
    subLayout.setAutoCreateGaps(true);

    subLayout.setHorizontalGroup(
        subLayout.createSequentialGroup()
            .addComponent(p2)
            .addComponent(p3)
    );

    subLayout.setVerticalGroup(
        subLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(p2)
            .addComponent(p3)
    );

    // ===== Xóa layout cũ =====
    getContentPane().removeAll();

    // ===== Layout chính =====
    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setAutoCreateGaps(true);
    layout.setAutoCreateContainerGaps(true);

    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(p1)
            .addComponent(p7)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p4)
                .addComponent(p5)
                .addComponent(p6)
            )
    );

    layout.setVerticalGroup(
        layout.createSequentialGroup()
            .addComponent(p1)
            .addComponent(p7)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(p4)
                .addComponent(p5)
                .addComponent(p6)
            )
    );

    revalidate();
    repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new baitap3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
