/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author admin
 */
public class bai10 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai10.class.getName());

    /**
     * Creates new form bai10
     */
    
    private JTextField txtUser;
    private JPasswordField txtPass;
    private JButton btnLogin;

    public bai10() {
        initComponents();     // KHÔNG SỬA
        initFormByCode();     // FORM TẠO BẰNG CODE
    }
     // ===== KHÔNG ĐƯỢC SỬA =====
    @SuppressWarnings("unchecked")
   
    // ===== FORM ĐĂNG NHẬP =====
    private void initFormByCode() {
        setTitle("Bài 10 - Đăng nhập");
        setSize(350, 200);
        setLocationRelativeTo(null);
        setLayout(new GridLayout(3, 2, 10, 10));

        JLabel lblUser = new JLabel("Username:");
        JLabel lblPass = new JLabel("Password:");

        txtUser = new JTextField();
        txtPass = new JPasswordField();

        btnLogin = new JButton("Đăng nhập");
        btnLogin.addActionListener(e -> xuLyDangNhap());

        add(lblUser);
        add(txtUser);
        add(lblPass);
        add(txtPass);
        add(new JLabel()); // ô trống
        add(btnLogin);
    }

    // ===== XỬ LÝ ĐĂNG NHẬP =====
    private void xuLyDangNhap() {
        String user = txtUser.getText().trim();
        String pass = new String(txtPass.getPassword());

        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không được để trống!",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Tài khoản mẫu
        if (user.equals("admin") && pass.equals("123456")) {
            hienDialogChaoMung(user);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Sai username hoặc password!",
                    "Đăng nhập thất bại",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // ===== JDialog CHÀO MỪNG =====
    private void hienDialogChaoMung(String user) {
        JDialog dialog = new JDialog(this, "Chào mừng", true);
        dialog.setSize(300, 150);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout());

        JLabel lblWelcome = new JLabel(
                "Xin chào " + user + "!",
                SwingConstants.CENTER);

        JButton btnOK = new JButton("OK");
        btnOK.addActionListener(e -> dialog.dispose());

        dialog.add(lblWelcome, BorderLayout.CENTER);
        dialog.add(btnOK, BorderLayout.SOUTH);

        dialog.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai10().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
