/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author admin
 */
public class bai1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai1.class.getName());

    /**
     * Creates new form bai1
     */
    
     public bai1() {
        initComponents();      // KHÔNG SỬA
        initFormByCode();      // TẠO FORM BẰNG CODE
    }
private JLabel lblHoTen;
    private JTextField txtHoTen;
    private JButton btnHienThi;
    private JLabel lblKetQua;
    // ===== FORM TẠO BẰNG CODE =====
    private void initFormByCode() {
        setTitle("Bài 1 - Nhập họ tên");
        setSize(400, 200);
        setLocationRelativeTo(null);

        // Layout
        setLayout(new GridLayout(4, 1, 10, 10));

        // Khởi tạo component
        lblHoTen = new JLabel("Họ tên:");
        txtHoTen = new JTextField();
        btnHienThi = new JButton("Hiển thị");
        lblKetQua = new JLabel(" ");

        // Sự kiện nút
        btnHienThi.addActionListener(e -> {
            String hoTen = txtHoTen.getText().trim();

            if (hoTen.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Họ tên không được để trống!",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE
                );
            } else {
                lblKetQua.setText("Họ tên: " + hoTen);
            }
        });

        // Thêm vào form
        add(lblHoTen);
        add(txtHoTen);
        add(btnHienThi);
        add(lblKetQua);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
