/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author admin
 */
public class bai2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai2.class.getName());

    /**
     * Creates new form bai2
     */
    // Khai báo component
    private JLabel lblMatKhau;
    private JPasswordField txtMatKhau;
    private JButton btnKiemTra;

    public bai2() {
        initComponents();      // KHÔNG SỬA
        initFormByCode();      // FORM BẰNG CODE
    }
// ===== FORM TẠO BẰNG CODE =====
    private void initFormByCode() {
        setTitle("Bài 2 - Kiểm tra mật khẩu");
        setSize(400, 180);
        setLocationRelativeTo(null);

        setLayout(new GridLayout(3, 1, 10, 10));

        lblMatKhau = new JLabel("Mật khẩu:");
        txtMatKhau = new JPasswordField();
        btnKiemTra = new JButton("Kiểm tra");

        btnKiemTra.addActionListener(e -> {
            char[] password = txtMatKhau.getPassword();

            if (password.length < 6) {
                JOptionPane.showMessageDialog(
                        this,
                        "Mật khẩu phải có ít nhất 6 ký tự!",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Mật khẩu hợp lệ!",
                        "Thành công",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }

            // Xóa mật khẩu sau khi kiểm tra (an toàn)
            txtMatKhau.setText("");
        });

        add(lblMatKhau);
        add(txtMatKhau);
        add(btnKiemTra);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
