/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author admin
 */
public class bai3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai3.class.getName());

    /**
     * Creates new form bai3
     */
    // Khai báo component
    private JCheckBox cbDocSach;
    private JCheckBox cbNgheNhac;
    private JCheckBox cbXemPhim;
    private JCheckBox cbDuLich;
    private JButton btnXacNhan;
    private JTextArea txtKetQua;

    public bai3() {
        initComponents();      // KHÔNG SỬA
        initFormByCode();      // FORM BẰNG CODE
    }
     // ===== FORM TẠO BẰNG CODE =====
    private void initFormByCode() {
        setTitle("Bài 3 - Chọn sở thích");
        setSize(400, 300);
        setLocationRelativeTo(null);

        setLayout(new BorderLayout(10, 10));

        // Panel chứa checkbox
        JPanel pnlCheckBox = new JPanel(new GridLayout(4, 1));
        cbDocSach = new JCheckBox("Đọc sách");
        cbNgheNhac = new JCheckBox("Nghe nhạc");
        cbXemPhim = new JCheckBox("Xem phim");
        cbDuLich = new JCheckBox("Du lịch");

        pnlCheckBox.add(cbDocSach);
        pnlCheckBox.add(cbNgheNhac);
        pnlCheckBox.add(cbXemPhim);
        pnlCheckBox.add(cbDuLich);

        // TextArea hiển thị kết quả
        txtKetQua = new JTextArea();
        txtKetQua.setEditable(false);
        JScrollPane scroll = new JScrollPane(txtKetQua);

        // Button xác nhận
        btnXacNhan = new JButton("Xác nhận");
        btnXacNhan.addActionListener(e -> {
            StringBuilder result = new StringBuilder("Sở thích đã chọn:\n");

            if (cbDocSach.isSelected()) result.append("- Đọc sách\n");
            if (cbNgheNhac.isSelected()) result.append("- Nghe nhạc\n");
            if (cbXemPhim.isSelected()) result.append("- Xem phim\n");
            if (cbDuLich.isSelected()) result.append("- Du lịch\n");

            txtKetQua.setText(result.toString());
        });

        // Thêm vào form
        add(pnlCheckBox, BorderLayout.WEST);
        add(scroll, BorderLayout.CENTER);
        add(btnXacNhan, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
