/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author admin
 */
public class bai4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai4.class.getName());

    /**
     * Creates new form bai4
     */
     // Khai báo component
    private JRadioButton rdNam;
    private JRadioButton rdNu;
    private JRadioButton rdKhac;
    private ButtonGroup groupGioiTinh;
    private JButton btnXacNhan;
    private JLabel lblKetQua;

    public bai4() {
        initComponents();      // KHÔNG SỬA
        initFormByCode();      // FORM BẰNG CODE
    }
     // ===== FORM TẠO BẰNG CODE =====
    private void initFormByCode() {
        setTitle("Bài 4 - Chọn giới tính");
        setSize(400, 220);
        setLocationRelativeTo(null);

        setLayout(new BorderLayout(10, 10));

        // RadioButton
        rdNam = new JRadioButton("Nam");
        rdNu = new JRadioButton("Nữ");
        rdKhac = new JRadioButton("Khác");

        // ButtonGroup (BẮT BUỘC)
        groupGioiTinh = new ButtonGroup();
        groupGioiTinh.add(rdNam);
        groupGioiTinh.add(rdNu);
        groupGioiTinh.add(rdKhac);

        // Panel chứa radio
        JPanel pnlRadio = new JPanel(new GridLayout(3, 1));
        pnlRadio.add(rdNam);
        pnlRadio.add(rdNu);
        pnlRadio.add(rdKhac);

        // Label kết quả
        lblKetQua = new JLabel("Giới tính: chưa chọn");

        // Button xác nhận
        btnXacNhan = new JButton("Xác nhận");
        btnXacNhan.addActionListener(e -> {
            String gioiTinh = "Chưa chọn";

            if (rdNam.isSelected()) gioiTinh = "Nam";
            else if (rdNu.isSelected()) gioiTinh = "Nữ";
            else if (rdKhac.isSelected()) gioiTinh = "Khác";

            lblKetQua.setText("Giới tính: " + gioiTinh);
        });

        // Thêm vào form
        add(pnlRadio, BorderLayout.WEST);
        add(btnXacNhan, BorderLayout.CENTER);
        add(lblKetQua, BorderLayout.SOUTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
