/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author admin
 */
public class bai6 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai6.class.getName());

    /**
     * Creates new form bai6
     */
     // Khai báo component
    private JTextField txtEmail;
    private JLabel lblThongBao;

    public bai6() {
        initComponents();      // KHÔNG SỬA
        initFormByCode();      // FORM BẰNG CODE
    }
      // ===== FORM TẠO BẰNG CODE =====
    private void initFormByCode() {
        setTitle("Bài 6 - Kiểm tra Email Realtime");
        setSize(450, 160);
        setLocationRelativeTo(null);

        setLayout(new GridLayout(3, 1, 10, 10));

        JLabel lblEmail = new JLabel("Email:");
        txtEmail = new JTextField();
        lblThongBao = new JLabel(" ");

        // Lắng nghe gõ phím realtime
        txtEmail.getDocument().addDocumentListener(new DocumentListener() {

            private void validateEmail() {
                String email = txtEmail.getText().trim();

                if (email.isEmpty()) {
                    lblThongBao.setText("Email không được để trống");
                    lblThongBao.setForeground(Color.RED);
                } else if (!isValidEmail(email)) {
                    lblThongBao.setText("Email không đúng định dạng");
                    lblThongBao.setForeground(Color.RED);
                } else {
                    lblThongBao.setText("Email hợp lệ");
                    lblThongBao.setForeground(new Color(0, 128, 0)); // xanh lá
                }
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                validateEmail();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateEmail();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateEmail();
            }
        });

        add(lblEmail);
        add(txtEmail);
        add(lblThongBao);
    }

    // ===== HÀM KIỂM TRA EMAIL =====
    private boolean isValidEmail(String email) {
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        return email.matches(regex);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai6().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
