/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author admin
 */
public class bai7 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai7.class.getName());

    /**
     * Creates new form bai7
     */
     // Khai báo component
    private JTextField txtTieuDe;
    private JTextArea txtNoiDung;
    private JButton btnGui;

    public bai7() {
        initComponents();      // KHÔNG SỬA
        initFormByCode();      // FORM BẰNG CODE
    }
// ===== FORM TẠO BẰNG CODE =====
    private void initFormByCode() {
        setTitle("Bài 7 - Phản hồi người dùng");
        setSize(500, 300);
        setLocationRelativeTo(null);

        setLayout(new BorderLayout(10, 10));

        // ===== PANEL TIÊU ĐỀ =====
        JPanel pnlTop = new JPanel(new BorderLayout(5, 5));
        pnlTop.add(new JLabel("Tiêu đề:"), BorderLayout.WEST);

        txtTieuDe = new JTextField();
        pnlTop.add(txtTieuDe, BorderLayout.CENTER);

        // ===== TEXTAREA NỘI DUNG =====
        txtNoiDung = new JTextArea();
        txtNoiDung.setLineWrap(true);
        txtNoiDung.setWrapStyleWord(true);
        JScrollPane scroll = new JScrollPane(txtNoiDung);

        // ===== BUTTON GỬI =====
        btnGui = new JButton("Gửi");
        btnGui.addActionListener(e -> xuLyGui());

        // ===== GHÉP FORM =====
        add(pnlTop, BorderLayout.NORTH);
        add(scroll, BorderLayout.CENTER);
        add(btnGui, BorderLayout.SOUTH);
    }

    // ===== XỬ LÝ GỬI =====
    private void xuLyGui() {
        String tieuDe = txtTieuDe.getText().trim();
        String noiDung = txtNoiDung.getText().trim();

        if (noiDung.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Nội dung phản hồi không được để trống!",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        JOptionPane.showMessageDialog(
                this,
                "Gửi phản hồi thành công!",
                "Thành công",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Xóa dữ liệu sau khi gửi
        txtTieuDe.setText("");
        txtNoiDung.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai7().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
