/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author admin
 */
public class bai8 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai8.class.getName());

    /**
     * Creates new form bai8
     */
    // Khai báo component
    private JLabel lblTitle;
    private JLabel lblMessage;
    private JButton btnViet;
    private JButton btnEnglish;

    public bai8() {
        initComponents();      // KHÔNG SỬA
        initFormByCode();      // FORM BẰNG CODE
    }
    // ===== FORM TẠO BẰNG CODE =====
    private void initFormByCode() {
        setTitle("Bài 8 - Đổi ngôn ngữ");
        setSize(400, 200);
        setLocationRelativeTo(null);

        setLayout(new BorderLayout(10, 10));

        // Label
        lblTitle = new JLabel("CHÀO MỪNG", SwingConstants.CENTER);
        lblTitle.setFont(new Font("Arial", Font.BOLD, 18));

        lblMessage = new JLabel("Chọn ngôn ngữ giao diện", SwingConstants.CENTER);

        // Button
        btnViet = new JButton("Tiếng Việt");
        btnEnglish = new JButton("English");

        btnViet.addActionListener(e -> chuyenTiengViet());
        btnEnglish.addActionListener(e -> chuyenEnglish());

        // Panel button
        JPanel pnlButton = new JPanel();
        pnlButton.add(btnViet);
        pnlButton.add(btnEnglish);

        // Add vào form
        add(lblTitle, BorderLayout.NORTH);
        add(lblMessage, BorderLayout.CENTER);
        add(pnlButton, BorderLayout.SOUTH);
    }

    // ===== CHUYỂN TIẾNG VIỆT =====
    private void chuyenTiengViet() {
        lblTitle.setText("CHÀO MỪNG");
        lblMessage.setText("Chọn ngôn ngữ giao diện");
        btnViet.setText("Tiếng Việt");
        btnEnglish.setText("English");
    }

    // ===== CHUYỂN TIẾNG ANH =====
    private void chuyenEnglish() {
        lblTitle.setText("WELCOME");
        lblMessage.setText("Select interface language");
        btnViet.setText("Vietnamese");
        btnEnglish.setText("English");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai8().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
