/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplab11;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author admin
 */
public class bai9 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai9.class.getName());

    /**
     * Creates new form bai9
     */
    
    private JButton btnDelete;

    public bai9() {
        initComponents();      // KHÔNG SỬA
        initFormByCode();      // FORM BẰNG CODE
    }
 // ===== FORM CHÍNH =====
    private void initFormByCode() {
        setTitle("Bài 9 - Xác nhận xóa");
        setSize(300, 150);
        setLocationRelativeTo(null);
        setLayout(new FlowLayout());

        btnDelete = new JButton("Xóa dữ liệu");
        btnDelete.addActionListener(e -> hienDialogXacNhan());

        add(btnDelete);
    }

    // ===== JDialog xác nhận =====
    private void hienDialogXacNhan() {
        JDialog dialog = new JDialog(this, "Xác nhận", true);
        dialog.setSize(300, 150);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout(10, 10));

        JLabel lblMessage = new JLabel("Bạn có chắc muốn xóa dữ liệu?", SwingConstants.CENTER);

        JButton btnOK = new JButton("Đồng ý");
        JButton btnCancel = new JButton("Hủy");

        btnOK.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Đã xóa dữ liệu!");
            dialog.dispose();
        });

        btnCancel.addActionListener(e -> dialog.dispose());

        JPanel pnlButton = new JPanel();
        pnlButton.add(btnOK);
        pnlButton.add(btnCancel);

        dialog.add(lblMessage, BorderLayout.CENTER);
        dialog.add(pnlButton, BorderLayout.SOUTH);

        dialog.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai9().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
